name = "day-sheet-dashboard"
main = "src/index.js"
compatibility_date = "2026-09-02"

[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "none"

[[kv_namespaces]]
binding = "DAY_SHEET_KV"
id = "f02d047a1e6b4cfeab61cd5e261effb0"
